(source "melpa")

(package "line-reminder" "0.5.1" "Line annotation for changed and saved lines")

(package-file "line-reminder.el")

(depends-on "emacs" "25.1")
(depends-on "indicators")
(depends-on "fringe-helper")
(depends-on "ov")
(depends-on "ht")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
